# Default values for flowing-retail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: "kafka-java-choreographed-shipping"
fullnameOverride: ""

image:
  repository: "flowingretail/kafka-java-choreography-shipping"
  tag: latest
  pullPolicy: IfNotPresent
  containerPort: 8092

service:
  port: 8092