version: "2"

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    hostname: zookeeper
    networks:
      - flowing
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    hostname: confluent-cp-kafka
    networks:
      - flowing
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://confluent-cp-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  checkout:
    image: flowingretail/kafka-java-checkout
    networks:
      - flowing
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  payment:
    image: flowingretail/kafka-java-choreography-payment
    networks:
      - flowing
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  inventory:
    image: flowingretail/kafka-java-choreography-inventory
    networks:
      - flowing
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  shipping:
    image: flowingretail/kafka-java-choreography-shipping
    networks:
      - flowing
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  monitor:
    image: flowingretail/kafka-java-monitor
    networks:
      - flowing
    ports:
      - "8095:8095"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  docs:
    image: flowingretail/docs
    networks:
      - flowing
    ports:
      - "8099:80"

  zeebe:
    image: camunda/zeebe:0.12.0-alpha4
    hostname: zeebe
    networks:
      - flowing
    ports:
      - "26500:26500"

  zeebe-track:
    image: flowingretail/kafka-java-choreography-zeebe-track
    networks:
      - flowing
    depends_on:
      - kafka
      - zeebe
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=confluent-cp-kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  zeebe-simple-monitor:
    image: flowingretail/zeebe-simple-monitor:latest
    hostname: zeebe
    networks:
      - flowing
    depends_on:
      - mongo
      - zeebe
    ports:
      - "8096:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo/flowingretail

  mongo:
    image: mongo
    hostname: mongo
    networks:
      - flowing
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  flowing:
    driver: bridge