# Default values for flowing-retail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: "kafka-java-orchestrated-shipping"
fullnameOverride: ""

image:
  repository: "flowingretail/kafka-java-orchestration-shipping"
  tag: latest
  pullPolicy: IfNotPresent